# Generated by Django 4.2 on 2024-03-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MewTable',
            new_name='NewTable',
        ),
    ]
