# Generated by Django 4.2 on 2024-06-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_1',
            name='device_list',
            field=models.CharField(choices=[('0', 'Android'), ('1', 'Apple')], default='0', max_length=1),
        ),
    ]
